Default: &defaults
  database: ShoeApi.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ShoeApi_test.sqlite3
  <<: *defaults

Staging:
  database: ShoeApi_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ShoeApi_production.sqlite3
  poolsize: 100
  <<: *defaults
